### ISSUE TITLE
Links are broken in readme

### ISSUE THREAD

**Issue by kishaningithub** [benoitkugler/go-weasyprint#6]
The links present in the readme for [webrender](https://github.com/benoitkugler/go-weasyprint/blob/master/github.com/benoitkugler/webrender) and [benoitkugler/pdf](https://github.com/benoitkugler/go-weasyprint/blob/master/github.com/benoitkugler/pdf) is broken

**Comment by benoitkugler** [comment]
Thank you !

**Comment by benoitkugler** [comment]
Fixed by 4b070e3
